# Generated by Django 2.2.16 on 2022-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220405_2220'),
    ]

    operations = [
        migrations.RenameField('Post', 'pub_date', 'created'),
    ]
